# Generated by Django 2.1.7 on 2020-09-20 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Quantative Aptitude', 'Quantative Aptitude'), ('Reasoning', 'Reasoning'), ('English', 'English')], max_length=50)),
                ('Difficulty_level', models.PositiveSmallIntegerField()),
                ('Question', models.CharField(max_length=512)),
                ('Option_A', models.CharField(max_length=256)),
                ('Option_B', models.CharField(max_length=256)),
                ('Option_C', models.CharField(max_length=256)),
                ('Option_D', models.CharField(max_length=256)),
                ('Answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('Answer_Description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='result_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=2048)),
                ('date_of_exam', models.DateTimeField(auto_now_add=True)),
                ('quest_list', models.CharField(default='', max_length=2048)),
                ('exam_name', models.CharField(max_length=256)),
                ('user_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='skills_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.levels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_name', models.CharField(max_length=256)),
                ('Position', models.CharField(max_length=256)),
                ('Difficulty_level', models.PositiveIntegerField()),
                ('Description', models.CharField(max_length=512)),
                ('number_of_questions', models.PositiveIntegerField()),
                ('question_number', models.ManyToManyField(to='question_app.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_marks', models.PositiveSmallIntegerField()),
                ('cm_position', models.CharField(max_length=256)),
                ('Test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Test_Information')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.result_user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('date_of_birth', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('education_filled', models.IntegerField(default=0)),
                ('Last_Highest_Education', models.CharField(choices=[('10th Class', '10th Class'), ('12th Class', '12th Class'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('Doctorate', 'Doctorate')], max_length=20)),
                ('School_or_College_Name', models.CharField(max_length=100)),
                ('Education_Percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('branch_of_graduation', models.CharField(max_length=50)),
                ('Skills_filled', models.IntegerField(default=0)),
                ('Govt_ID_type', models.CharField(choices=[('PAN card', 'PAN card'), ('Aadhar card', 'Aadhar number'), ('Driving License', 'Driving License'), ('Voter ID', 'Voter_ID')], max_length=20)),
                ('Govt_ID_number', models.CharField(max_length=30)),
                ('Prfoile_verification_filled', models.IntegerField(default=0)),
                ('Main_Hobbies', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
